import { writeFileSync } from 'node:fs';
import { CITATION_PROFANITY_PATTERN } from '../src/lib/citationLanguage.ts';

const sql = `-- Generated by scripts/generate-citation-language.ts. Do not hand-edit the pattern.
-- Run after app_citations_migration.sql, before deploying the language-check client.
-- Existing matches are hidden for review, not deleted. No live migration runs automatically.
BEGIN;
CREATE OR REPLACE FUNCTION public.citation_contains_profanity(value text)
RETURNS boolean LANGUAGE sql IMMUTABLE STRICT SET search_path=pg_catalog AS $function$
  SELECT normalize(value, NFKC) ~* $pattern$${CITATION_PROFANITY_PATTERN}$pattern$;
$function$;

-- Keep rows and ownership intact. Moderators can inspect hidden rows and request rephrasing.
UPDATE public.app_citations SET is_hidden=true
WHERE NOT is_hidden AND (
  public.citation_contains_profanity(display_name)
  OR public.citation_contains_profanity(use_case)
  OR public.citation_contains_profanity(feedback)
);

CREATE OR REPLACE FUNCTION public.check_citation_language()
RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $function$
BEGIN
  -- Moderators must still be able to hide an unchanged legacy citation.
  IF TG_OP='UPDATE' THEN
    IF NEW.is_hidden AND NEW.display_name IS NOT DISTINCT FROM OLD.display_name
      AND NEW.use_case IS NOT DISTINCT FROM OLD.use_case
      AND NEW.feedback IS NOT DISTINCT FROM OLD.feedback THEN
      RETURN NEW;
    END IF;
  END IF;
  IF public.citation_contains_profanity(NEW.display_name)
    OR public.citation_contains_profanity(NEW.use_case)
    OR public.citation_contains_profanity(NEW.feedback) THEN
    RAISE EXCEPTION USING ERRCODE='P0001', MESSAGE='CITATION_PROFANITY: Please rephrase without profanity.';
  END IF;
  RETURN NEW;
END;
$function$;
DROP TRIGGER IF EXISTS citation_language_check ON public.app_citations;
CREATE TRIGGER citation_language_check
BEFORE INSERT OR UPDATE OF display_name,use_case,feedback,is_hidden ON public.app_citations
FOR EACH ROW EXECUTE FUNCTION public.check_citation_language();
COMMIT;
`;
writeFileSync(new URL('../docs/citation_language_migration.sql', import.meta.url), sql);
